[package]
name = "restrust"
version = "0.1.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]

[dependencies]
iron="*"
persistent="*"
router = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
postgres = "0.10"
r2d2="*"
r2d2_postgres="*"
